### ISSUE TITLE
Error on attempting to use the button

### ISSUE THREAD

**Issue by INTONIGHT** [INTONIGHT/SeniorCapstone#1]
On clcicking create spreadhseet in the console it gives an error that I was not sure how to figure out. I am trying to read data froma  JSON file and eventually manipulate said data.

**Comment by ericsaupe** [comment]
There are a few things happening and not happening here.

First, you aren't ever actually making the call with the `request`. You initialize the request and set some callbacks to happen when the state changes here https://github.com/INTONIGHT/SeniorCapstone/blob/master/home.js#L6-L15 but you never `send` the request. Adding `request.send();` to line 16 will make the request happen.

See https://www.w3schools.com/js/js_ajax_http_send.asp for reference.

The next issue you'll run into is that sending the request will actually fail and the error you'll see in the browser console is this:

```
Access to XMLHttpRequest at 'file:///Users/eric/code/personal/SeniorCapstone/store.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
```

Obviously the file path will be different on your machine but that's the error you'll see. That error is a protection that all modern browsers have in place as a security precaution around malicious websites accessing local files on someones file system. In your case you aren't doing anything nefarious but the browser doesn't know that. Browsers restrict requests for files to be restricted to addresses with `http` or `https` and not `file`. The only way to fix this is to actually run a web server.

See https://stackoverflow.com/questions/10752055/cross-origin-requests-are-only-supported-for-http-error-when-loading-a-local for reference.

Since you are already using a modern javascript implementation (judging by your `package-lock.json` file, I'm assuming you have `npm` ready. With that you can quickly run a web server by installing the `http-server` package with this command `npm install -g http-server`.

See https://stackoverflow.com/a/21608670/575985 under `Node.js` for reference.

Once that is installed and running (to run the server just follow the commands either in that stackoverflow answer or from the `http-server` documentation) you should be able to access your page and file without issue. I was able to get it running locally following everything I wrote above.

As an added bit of proper programming since you are installing packages that your app relies on you should probably create a `package.json` file to let others who download your app know what needs to be installed. Updating your `README` with commands on how to run the server and use the app is also helpful.

See https://docs.npmjs.com/creating-a-package-json-file and https://docs.npmjs.com/configuring-npm/package-lock-json.html for reference.

Hope this helps.

**Comment by INTONIGHT** [comment]
SO i got the npm working and the line of code and http installed however when trying to run http-server i got the following error
![Screenshot_59](https://user-images.githubusercontent.com/71537873/96825683-b89fca00-13ff-11eb-8e8e-c2067b4513a6.png)

**Comment by cougswin1** [comment]
Try running this first - Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted

**Comment by INTONIGHT** [comment]
Ok that worked for creating the http server though the actualcreate spreadsheet doesnt work with no errors showing up so unsure why its breaking
